// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function operator(time, scheduler) {
  return /* record */[/* subscribeWith */(function (obs) {
              var alive = /* record */[/* contents */true];
              var timerSub = Curry._2(scheduler[/* timeout */1], (function (param) {
                      if (alive[0]) {
                        return Curry._1(obs[/* onSuccess */1], 0);
                      } else {
                        return 0;
                      }
                    }), time);
              return Curry._1(obs[/* onSubscribe */0], /* record */[/* cancel */(function (param) {
                              if (alive[0]) {
                                Curry._1(timerSub[/* cancel */0], /* () */0);
                                alive[0] = false;
                                return /* () */0;
                              } else {
                                return 0;
                              }
                            })]);
            })];
}

exports.operator = operator;
/* No side effect */
