// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedSingleObserver$Reaxon = require("../../Observers/ProtectedSingleObserver.bs.js");

function operator(other, combiner, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var sourceSub = {
                contents: undefined
              };
              var otherSub = {
                contents: undefined
              };
              var aValue = {
                contents: undefined
              };
              var bValue = {
                contents: undefined
              };
              var subscription = {
                cancel: (function (param) {
                    if (alive.contents) {
                      OptionalSubscription$Reaxon.cancel(sourceSub.contents);
                      OptionalSubscription$Reaxon.cancel(otherSub.contents);
                      alive.contents = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })
              };
              Curry._1(obs.onSubscribe, subscription);
              var combine = function (a, b) {
                var exit = 0;
                var result;
                try {
                  result = Curry._2(combiner, a, b);
                  exit = 1;
                }
                catch (raw_e){
                  Curry._1(obs.onError, Caml_js_exceptions.internalToOCamlException(raw_e));
                }
                if (exit === 1) {
                  Curry._1(obs.onSuccess, result);
                }
                return Curry._1(subscription.cancel, /* () */0);
              };
              Curry._1(source.subscribeWith, ProtectedSingleObserver$Reaxon.make({
                        onSubscribe: (function (sub) {
                            if (alive.contents) {
                              sourceSub.contents = sub;
                              return /* () */0;
                            } else {
                              return Curry._1(sub.cancel, /* () */0);
                            }
                          }),
                        onSuccess: (function (x) {
                            if (alive.contents) {
                              var match = bValue.contents;
                              if (match !== undefined) {
                                return combine(x, Caml_option.valFromOption(match));
                              } else {
                                aValue.contents = Caml_option.some(x);
                                return /* () */0;
                              }
                            } else {
                              return 0;
                            }
                          }),
                        onError: (function (x) {
                            if (alive.contents) {
                              Curry._1(obs.onError, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              throw x;
                            }
                          })
                      }));
              return Curry._1(other.subscribeWith, ProtectedSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    otherSub.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onSuccess: (function (x) {
                                  if (alive.contents) {
                                    var match = aValue.contents;
                                    if (match !== undefined) {
                                      return combine(Caml_option.valFromOption(match), x);
                                    } else {
                                      bValue.contents = Caml_option.some(x);
                                      return /* () */0;
                                    }
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
