// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(resumeFunction, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(source[/* subscribeWith */0], SafeSingleObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onSuccess */(function (x) {
                                  return Curry._1(obs[/* onSuccess */1], x);
                                }),
                              /* onError */(function (x) {
                                  var item;
                                  try {
                                    item = Curry._1(resumeFunction, x);
                                  }
                                  catch (raw_e){
                                    return Curry._1(obs[/* onError */2], Caml_js_exceptions.internalToOCamlException(raw_e));
                                  }
                                  return Curry._1(obs[/* onSuccess */1], item);
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
