// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedSingleObserver$Reaxon = require("../../Observers/ProtectedSingleObserver.bs.js");

function operator(other, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var sourceSub = {
                contents: undefined
              };
              var otherSub = {
                contents: undefined
              };
              var subscription = {
                cancel: (function (param) {
                    if (alive.contents) {
                      OptionalSubscription$Reaxon.cancel(sourceSub.contents);
                      OptionalSubscription$Reaxon.cancel(otherSub.contents);
                      alive.contents = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })
              };
              Curry._1(source.subscribeWith, ProtectedSingleObserver$Reaxon.make({
                        onSubscribe: (function (sub) {
                            if (alive.contents) {
                              sourceSub.contents = sub;
                              return /* () */0;
                            } else {
                              return Curry._1(sub.cancel, /* () */0);
                            }
                          }),
                        onSuccess: (function (x) {
                            if (alive.contents) {
                              Curry._1(obs.onSuccess, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              return 0;
                            }
                          }),
                        onError: (function (x) {
                            if (alive.contents) {
                              Curry._1(obs.onError, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              throw x;
                            }
                          })
                      }));
              return Curry._1(other.subscribeWith, ProtectedSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    otherSub.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onSuccess: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onSuccess, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
