// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SingleError$Reaxon = require("./SingleError.bs.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(supplier) {
  return /* record */[/* subscribeWith */(function (obs) {
              var result;
              try {
                result = Curry._1(supplier, /* () */0);
              }
              catch (raw_e){
                var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                return Curry._1(SingleError$Reaxon.operator(e)[/* subscribeWith */0], obs);
              }
              return Curry._1(result[/* subscribeWith */0], SafeSingleObserver$Reaxon.make(obs));
            })];
}

exports.operator = operator;
/* No side effect */
