// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(scheduler, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, {
                                              cancel: (function (param) {
                                                  if (alive.contents) {
                                                    Curry._1(scheduler.run, (function (param) {
                                                            return Curry._1(sub.cancel, /* () */0);
                                                          }));
                                                    alive.contents = false;
                                                    return /* () */0;
                                                  } else {
                                                    return 0;
                                                  }
                                                })
                                            });
                                }),
                              onSuccess: (function (x) {
                                  return Curry._1(obs.onSuccess, x);
                                }),
                              onError: (function (x) {
                                  return Curry._1(obs.onError, x);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
