// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(source[/* subscribeWith */0], SafeSingleObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onSuccess */(function (x) {
                                  return Curry._1(obs[/* onSuccess */1], /* OnSuccess */Block.__(0, [x]));
                                }),
                              /* onError */(function (x) {
                                  return Curry._1(obs[/* onSuccess */1], /* OnError */Block.__(1, [x]));
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
