// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onSuccess: (function (x) {
                                  return Curry._1(obs.onSuccess, /* OnSuccess */Block.__(0, [x]));
                                }),
                              onError: (function (x) {
                                  return Curry._1(obs.onSuccess, /* OnError */Block.__(1, [x]));
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
