// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var EmptySubscription$Reaxon = require("../../Utils/EmptySubscription.bs.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(value) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              Curry._1(safe[/* onSubscribe */0], EmptySubscription$Reaxon.instance);
              return Curry._1(safe[/* onError */2], value);
            })];
}

exports.operator = operator;
/* No side effect */
