// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(onEvent, source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onSuccess: (function (x) {
                                  Curry._2(onEvent, Caml_option.some(x), undefined);
                                  return Curry._1(obs.onSuccess, x);
                                }),
                              onError: (function (x) {
                                  Curry._2(onEvent, undefined, x);
                                  return Curry._1(obs.onError, x);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
