// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(scheduler, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var alive = /* record */[/* contents */true];
              return Curry._1(source[/* subscribeWith */0], SafeSingleObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], /* record */[/* cancel */(function (param) {
                                                  if (alive[0]) {
                                                    Curry._1(scheduler[/* run */0], (function (param) {
                                                            return Curry._1(sub[/* cancel */0], /* () */0);
                                                          }));
                                                    alive[0] = false;
                                                    return /* () */0;
                                                  } else {
                                                    return 0;
                                                  }
                                                })]);
                                }),
                              /* onSuccess */(function (x) {
                                  return Curry._1(obs[/* onSuccess */1], x);
                                }),
                              /* onError */(function (x) {
                                  return Curry._1(obs[/* onError */2], x);
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
