// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function operator(time, scheduler) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var timerSub = Curry._2(scheduler.timeout, (function (param) {
                      if (alive.contents) {
                        return Curry._1(obs.onSuccess, 0);
                      } else {
                        return 0;
                      }
                    }), time);
              return Curry._1(obs.onSubscribe, {
                          cancel: (function (param) {
                              if (alive.contents) {
                                Curry._1(timerSub.cancel, /* () */0);
                                alive.contents = false;
                                return /* () */0;
                              } else {
                                return 0;
                              }
                            })
                        });
            })
        };
}

exports.operator = operator;
/* No side effect */
