// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SingleError$Reaxon = require("./SingleError.bs.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(operator$1, source) {
  return {
          subscribeWith: (function (obs) {
              var result;
              try {
                result = Curry._1(operator$1, obs);
              }
              catch (raw_exn){
                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                return Curry._1(SingleError$Reaxon.operator(exn).subscribeWith, obs);
              }
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make(result));
            })
        };
}

exports.operator = operator;
/* No side effect */
