// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var OptionalSubscription$Reaxon = require("./OptionalSubscription.bs.js");

function make(param) {
  var alive = {
    contents: true
  };
  var outerRef = {
    contents: undefined
  };
  var innerRef = {
    contents: undefined
  };
  var subscription = {
    cancel: (function (param) {
        if (alive.contents) {
          OptionalSubscription$Reaxon.cancel(outerRef.contents);
          OptionalSubscription$Reaxon.cancel(innerRef.contents);
          alive.contents = false;
          return /* () */0;
        } else {
          return 0;
        }
      })
  };
  return /* tuple */[
          alive,
          outerRef,
          innerRef,
          subscription
        ];
}

exports.make = make;
/* No side effect */
