// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var instance = {
  cancel: (function (param) {
      return /* () */0;
    })
};

exports.instance = instance;
/* No side effect */
