// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function cancel(sub) {
  if (sub !== undefined) {
    return Curry._1(sub.cancel, /* () */0);
  } else {
    return /* () */0;
  }
}

exports.cancel = cancel;
/* No side effect */
