// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (param) {
              var onComplete = param.onComplete;
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                              onSubscribe: param.onSubscribe,
                              onSuccess: (function (param) {
                                  return Curry._1(onComplete, /* () */0);
                                }),
                              onError: param.onError
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
