// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeCompletableObserver$Reaxon = require("../../Observers/SafeCompletableObserver.bs.js");

function operator(supplier) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeCompletableObserver$Reaxon.make(obs);
              try {
                Curry._1(supplier, /* () */0);
              }
              catch (raw_e){
                Curry._1(safe[/* onError */2], Caml_js_exceptions.internalToOCamlException(raw_e));
              }
              return Curry._1(safe[/* onComplete */1], /* () */0);
            })];
}

exports.operator = operator;
/* No side effect */
