// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var DoubleSubscription$Reaxon = require("../../Utils/DoubleSubscription.bs.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");
var SafeCompletableObserver$Reaxon = require("../../Observers/SafeCompletableObserver.bs.js");

function operator(other, source) {
  return {
          subscribeWith: (function (param) {
              var onNext = param.onNext;
              var onError = param.onError;
              var onComplete = param.onComplete;
              var match = DoubleSubscription$Reaxon.make(/* () */0);
              var subscription = match[3];
              var right = match[2];
              var left = match[1];
              var alive = match[0];
              var aFinished = {
                contents: false
              };
              var bFinished = {
                contents: false
              };
              Curry._1(param.onSubscribe, subscription);
              Curry._1(source.subscribeWith, SafeCompletableObserver$Reaxon.make({
                        onSubscribe: (function (sub) {
                            if (alive.contents) {
                              left.contents = sub;
                              return /* () */0;
                            } else {
                              return Curry._1(sub.cancel, /* () */0);
                            }
                          }),
                        onComplete: (function (param) {
                            if (alive.contents) {
                              aFinished.contents = true;
                              if (bFinished.contents) {
                                Curry._1(onComplete, /* () */0);
                                return Curry._1(subscription.cancel, /* () */0);
                              } else {
                                return 0;
                              }
                            } else {
                              return 0;
                            }
                          }),
                        onError: (function (x) {
                            if (alive.contents) {
                              Curry._1(onError, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              throw x;
                            }
                          })
                      }));
              return Curry._1(other.subscribeWith, SafeObservableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    right.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onComplete: (function (param) {
                                  if (alive.contents) {
                                    bFinished.contents = true;
                                    if (aFinished.contents) {
                                      Curry._1(onComplete, /* () */0);
                                      return Curry._1(subscription.cancel, /* () */0);
                                    } else {
                                      return 0;
                                    }
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                }),
                              onNext: Curry.__1(onNext)
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
