// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(source[/* subscribeWith */0], SafeSingleObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onSuccess */(function (x) {
                                  if (x) {
                                    return Curry._1(obs[/* onError */2], x[0]);
                                  } else {
                                    return Curry._1(obs[/* onComplete */1], /* () */0);
                                  }
                                }),
                              /* onError */(function (x) {
                                  return Curry._1(obs[/* onError */2], x);
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
