// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeCompletableObserver$Reaxon = require("../../Observers/SafeCompletableObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (param) {
              var onSuccess = param.onSuccess;
              return Curry._1(source.subscribeWith, SafeCompletableObserver$Reaxon.make({
                              onSubscribe: param.onSubscribe,
                              onComplete: (function (param) {
                                  return Curry._1(onSuccess, /* OnComplete */0);
                                }),
                              onError: (function (x) {
                                  return Curry._1(onSuccess, /* OnError */[x]);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
