// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeCompletableObserver$Reaxon = require("../../Observers/SafeCompletableObserver.bs.js");

function operator(supplier, source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeCompletableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onComplete: (function (param) {
                                  var item;
                                  try {
                                    item = Curry._1(supplier, /* () */0);
                                  }
                                  catch (raw_e){
                                    return Curry._1(obs.onError, Caml_js_exceptions.internalToOCamlException(raw_e));
                                  }
                                  return Curry._1(obs.onSuccess, item);
                                }),
                              onError: (function (x) {
                                  return Curry._1(obs.onError, x);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
