// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Exceptions$Reaxon = require("../../Exceptions.bs.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              var last = /* record */[/* contents */undefined];
              var single = /* record */[/* contents */false];
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (sub) {
                              return Curry._1(safe[/* onSubscribe */0], sub);
                            }),
                          /* onComplete */(function (param) {
                              if (single[0]) {
                                var match = last[0];
                                if (match !== undefined) {
                                  return Curry._1(safe[/* onSuccess */1], Caml_option.valFromOption(match));
                                } else {
                                  return Curry._1(safe[/* onError */2], Exceptions$Reaxon.NoSuchElement);
                                }
                              } else {
                                return Curry._1(safe[/* onError */2], Exceptions$Reaxon.NoSuchElement);
                              }
                            }),
                          /* onError */(function (x) {
                              return Curry._1(safe[/* onError */2], x);
                            }),
                          /* onNext */(function (x) {
                              if (single[0]) {
                                return Curry._1(safe[/* onError */2], Exceptions$Reaxon.IndexOutOfBounds);
                              } else {
                                single[0] = true;
                                last[0] = Caml_option.some(x);
                                return /* () */0;
                              }
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
