// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(filter, source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onSuccess: (function (x) {
                                  var val;
                                  try {
                                    val = Curry._1(filter, x);
                                  }
                                  catch (raw_e){
                                    return Curry._1(obs.onError, Caml_js_exceptions.internalToOCamlException(raw_e));
                                  }
                                  if (val) {
                                    return Curry._1(obs.onSuccess, x);
                                  } else {
                                    return Curry._1(obs.onComplete, /* () */0);
                                  }
                                }),
                              onError: (function (x) {
                                  return Curry._1(obs.onError, x);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
