// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(supplier) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              var item;
              try {
                item = Curry._1(supplier, /* () */0);
              }
              catch (raw_e){
                return Curry._1(safe[/* onError */2], Caml_js_exceptions.internalToOCamlException(raw_e));
              }
              return Curry._1(safe[/* onSuccess */1], item);
            })];
}

exports.operator = operator;
/* No side effect */
