// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedCompletableObserver$Reaxon = require("../../Observers/ProtectedCompletableObserver.bs.js");

function operator(other, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var aFinished = {
                contents: false
              };
              var bFinished = {
                contents: false
              };
              var aRef = {
                contents: undefined
              };
              var bRef = {
                contents: undefined
              };
              var subscription = {
                cancel: (function (param) {
                    if (alive.contents) {
                      OptionalSubscription$Reaxon.cancel(aRef.contents);
                      OptionalSubscription$Reaxon.cancel(bRef.contents);
                      alive.contents = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })
              };
              Curry._1(obs.onSubscribe, subscription);
              Curry._1(source.subscribeWith, SafeSingleObserver$Reaxon.make({
                        onSubscribe: (function (sub) {
                            if (alive.contents) {
                              aRef.contents = sub;
                              return /* () */0;
                            } else {
                              return Curry._1(sub.cancel, /* () */0);
                            }
                          }),
                        onSuccess: (function (x) {
                            if (alive.contents) {
                              aFinished.contents = true;
                              Curry._1(obs.onNext, x);
                              if (alive.contents && bFinished.contents) {
                                Curry._1(obs.onComplete, /* () */0);
                                return Curry._1(subscription.cancel, /* () */0);
                              } else {
                                return 0;
                              }
                            } else {
                              return 0;
                            }
                          }),
                        onError: (function (x) {
                            if (alive.contents) {
                              Curry._1(obs.onError, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              throw x;
                            }
                          })
                      }));
              return Curry._1(other.subscribeWith, ProtectedCompletableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    bRef.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onComplete: (function (param) {
                                  if (alive.contents) {
                                    bFinished.contents = true;
                                    if (alive.contents && aFinished.contents) {
                                      Curry._1(obs.onComplete, /* () */0);
                                      return Curry._1(subscription.cancel, /* () */0);
                                    } else {
                                      return 0;
                                    }
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
