// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(obs) {
  var subscribed = /* record */[/* contents */false];
  return /* record */[
          /* onSubscribe */(function (sub) {
              if (subscribed[0]) {
                return Curry._1(sub[/* cancel */0], /* () */0);
              } else {
                subscribed[0] = true;
                return Curry._1(obs[/* onSubscribe */0], sub);
              }
            }),
          /* onSuccess */(function (x) {
              if (subscribed[0]) {
                return Curry._1(obs[/* onSuccess */1], x);
              } else {
                return 0;
              }
            }),
          /* onError */(function (x) {
              if (subscribed[0]) {
                return Curry._1(obs[/* onError */2], x);
              } else {
                return 0;
              }
            })
        ];
}

exports.make = make;
/* No side effect */
