// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(obs) {
  var subscribed = {
    contents: false
  };
  return {
          onSubscribe: (function (sub) {
              if (subscribed.contents) {
                return Curry._1(sub.cancel, /* () */0);
              } else {
                subscribed.contents = true;
                return Curry._1(obs.onSubscribe, sub);
              }
            }),
          onComplete: (function (param) {
              if (subscribed.contents) {
                return Curry._1(obs.onComplete, /* () */0);
              } else {
                return 0;
              }
            }),
          onError: (function (x) {
              if (subscribed.contents) {
                return Curry._1(obs.onError, x);
              } else {
                throw x;
              }
            }),
          onNext: (function (x) {
              if (subscribed.contents) {
                return Curry._1(obs.onNext, x);
              } else {
                return 0;
              }
            })
        };
}

exports.make = make;
/* No side effect */
