// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var OptionalSubscription$Reaxon = require("../Utils/OptionalSubscription.bs.js");
var ProtectedSingleObserver$Reaxon = require("./ProtectedSingleObserver.bs.js");

function make(obs) {
  var alive = {
    contents: true
  };
  var subRef = {
    contents: undefined
  };
  var subscription = {
    cancel: (function (param) {
        if (alive.contents) {
          OptionalSubscription$Reaxon.cancel(subRef.contents);
          alive.contents = false;
          return /* () */0;
        } else {
          return 0;
        }
      })
  };
  return ProtectedSingleObserver$Reaxon.make({
              onSubscribe: (function (sub) {
                  if (alive.contents) {
                    subRef.contents = sub;
                    return Curry._1(obs.onSubscribe, subscription);
                  } else {
                    return Curry._1(sub.cancel, /* () */0);
                  }
                }),
              onSuccess: (function (x) {
                  if (alive.contents) {
                    Curry._1(obs.onSuccess, x);
                    return Curry._1(subscription.cancel, /* () */0);
                  } else {
                    return 0;
                  }
                }),
              onError: (function (x) {
                  if (alive.contents) {
                    Curry._1(obs.onError, x);
                    return Curry._1(subscription.cancel, /* () */0);
                  } else {
                    throw x;
                  }
                })
            });
}

exports.make = make;
/* No side effect */
