// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeMaybeObserver$Reaxon = require("../../Observers/SafeMaybeObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeMaybeObserver$Reaxon.make(obs);
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (sub) {
                              return Curry._1(safe[/* onSubscribe */0], sub);
                            }),
                          /* onComplete */(function (param) {
                              return Curry._1(safe[/* onComplete */1], /* () */0);
                            }),
                          /* onError */(function (x) {
                              return Curry._1(safe[/* onError */3], x);
                            }),
                          /* onNext */(function (x) {
                              return Curry._1(safe[/* onSuccess */2], x);
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
