// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Exceptions$Reaxon = require("../../Exceptions.bs.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              return Curry._1(source.subscribeWith, {
                          onSubscribe: (function (sub) {
                              return Curry._1(safe.onSubscribe, sub);
                            }),
                          onComplete: (function (param) {
                              return Curry._1(safe.onError, Exceptions$Reaxon.NoSuchElement);
                            }),
                          onError: (function (x) {
                              return Curry._1(safe.onError, x);
                            }),
                          onNext: (function (x) {
                              return Curry._1(safe.onSuccess, x);
                            })
                        });
            })
        };
}

exports.operator = operator;
/* No side effect */
