// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var array = /* record */[/* contents : array */[]];
              var safe = SafeSingleObserver$Reaxon.make(obs);
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (sub) {
                              return Curry._1(safe[/* onSubscribe */0], sub);
                            }),
                          /* onComplete */(function (param) {
                              return Curry._1(safe[/* onSuccess */1], array[0]);
                            }),
                          /* onError */(function (x) {
                              return Curry._1(safe[/* onError */2], x);
                            }),
                          /* onNext */(function (x) {
                              array[0] = $$Array.concat(/* :: */[
                                    array[0],
                                    /* :: */[
                                      /* array */[x],
                                      /* [] */0
                                    ]
                                  ]);
                              return /* () */0;
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
