// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              return Curry._1(source.subscribeWith, {
                          onSubscribe: (function (subscription) {
                              return Curry._1(safe.onSubscribe, subscription);
                            }),
                          onComplete: (function (param) {
                              return Curry._1(safe.onSuccess, 0);
                            }),
                          onSuccess: (function (param) {
                              return Curry._1(safe.onSuccess, 1);
                            }),
                          onError: (function (err) {
                              return Curry._1(safe.onError, err);
                            })
                        });
            })
        };
}

exports.operator = operator;
/* No side effect */
