// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeSingleObserver$Reaxon = require("../../Observers/SafeSingleObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeSingleObserver$Reaxon.make(obs);
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (subscription) {
                              return Curry._1(safe[/* onSubscribe */0], subscription);
                            }),
                          /* onComplete */(function (param) {
                              return Curry._1(safe[/* onSuccess */1], 0);
                            }),
                          /* onSuccess */(function (param) {
                              return Curry._1(safe[/* onSuccess */1], 1);
                            }),
                          /* onError */(function (err) {
                              return Curry._1(safe[/* onError */2], err);
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
