// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeMaybeObserver$Reaxon = require("../../Observers/SafeMaybeObserver.bs.js");

function operator(onError, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(source[/* subscribeWith */0], SafeMaybeObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onComplete */(function (param) {
                                  return Curry._1(obs[/* onComplete */1], /* () */0);
                                }),
                              /* onSuccess */(function (x) {
                                  return Curry._1(obs[/* onSuccess */2], x);
                                }),
                              /* onError */(function (x) {
                                  Curry._1(onError, x);
                                  return Curry._1(obs[/* onError */3], x);
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
