// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function operator(time, scheduler) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(obs[/* onSubscribe */0], Curry._2(scheduler[/* timeout */1], (function (param) {
                                return Curry._1(obs[/* onSuccess */2], 0);
                              }), time));
            })];
}

exports.operator = operator;
/* No side effect */
