// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function operator(time, scheduler) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(obs.onSubscribe, Curry._2(scheduler.timeout, (function (param) {
                                return Curry._1(obs.onSuccess, 0);
                              }), time));
            })
        };
}

exports.operator = operator;
/* No side effect */
