// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var MaybeError$Reaxon = require("./MaybeError.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeMaybeObserver$Reaxon = require("../../Observers/SafeMaybeObserver.bs.js");

function operator(operator$1, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var result;
              try {
                result = Curry._1(operator$1, obs);
              }
              catch (raw_exn){
                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                return Curry._1(MaybeError$Reaxon.operator(exn)[/* subscribeWith */0], obs);
              }
              return Curry._1(source[/* subscribeWith */0], SafeMaybeObserver$Reaxon.make(result));
            })];
}

exports.operator = operator;
/* No side effect */
