// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var EmptySubscription$Reaxon = require("../../Utils/EmptySubscription.bs.js");
var SafeMaybeObserver$Reaxon = require("../../Observers/SafeMaybeObserver.bs.js");

var instance = /* record */[/* subscribeWith */(function (obs) {
      var safe = SafeMaybeObserver$Reaxon.make(obs);
      Curry._1(safe[/* onSubscribe */0], EmptySubscription$Reaxon.instance);
      return Curry._1(safe[/* onComplete */1], /* () */0);
    })];

function operator(param) {
  return instance;
}

exports.instance = instance;
exports.operator = operator;
/* No side effect */
