// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Cancellation = Caml_exceptions.create("Exceptions-Reaxon.Cancellation");

var Timeout = Caml_exceptions.create("Exceptions-Reaxon.Timeout");

var IndexOutOfBounds = Caml_exceptions.create("Exceptions-Reaxon.IndexOutOfBounds");

var NoSuchElement = Caml_exceptions.create("Exceptions-Reaxon.NoSuchElement");

var MultiSubscription = Caml_exceptions.create("Exceptions-Reaxon.MultiSubscription");

var Interrupted = Caml_exceptions.create("Exceptions-Reaxon.Interrupted");

exports.Cancellation = Cancellation;
exports.Timeout = Timeout;
exports.IndexOutOfBounds = IndexOutOfBounds;
exports.NoSuchElement = NoSuchElement;
exports.MultiSubscription = MultiSubscription;
exports.Interrupted = Interrupted;
/* No side effect */
