// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Subscription = { };

var Lambda = { };

var Observer = {
  Lambda: Lambda
};

var Emitter = { };

var $$Notification = { };

var Single = {
  Observer: Observer,
  Emitter: Emitter,
  $$Notification: $$Notification
};

var Lambda$1 = { };

var Observer$1 = {
  Lambda: Lambda$1
};

var Emitter$1 = { };

var $$Notification$1 = { };

var Completable = {
  Observer: Observer$1,
  Emitter: Emitter$1,
  $$Notification: $$Notification$1
};

var Lambda$2 = { };

var Observer$2 = {
  Lambda: Lambda$2
};

var Emitter$2 = { };

var $$Notification$2 = { };

var Maybe = {
  Observer: Observer$2,
  Emitter: Emitter$2,
  $$Notification: $$Notification$2
};

var Lambda$3 = { };

var Observer$3 = {
  Lambda: Lambda$3
};

var Emitter$3 = { };

var $$Notification$3 = { };

var Observable = {
  Observer: Observer$3,
  Emitter: Emitter$3,
  $$Notification: $$Notification$3
};

var Scheduler = { };

exports.Subscription = Subscription;
exports.Single = Single;
exports.Completable = Completable;
exports.Maybe = Maybe;
exports.Observable = Observable;
exports.Scheduler = Scheduler;
/* No side effect */
