// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedObservableObserver$Reaxon = require("../../Observers/ProtectedObservableObserver.bs.js");

function operator(other, combiner, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var sourceSub = {
                contents: undefined
              };
              var otherSub = {
                contents: undefined
              };
              var aValues = {
                contents: /* [] */0
              };
              var bValues = {
                contents: /* [] */0
              };
              var subscription = {
                cancel: (function (param) {
                    if (alive.contents) {
                      OptionalSubscription$Reaxon.cancel(sourceSub.contents);
                      OptionalSubscription$Reaxon.cancel(otherSub.contents);
                      alive.contents = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })
              };
              Curry._1(obs.onSubscribe, subscription);
              var combine = function (param) {
                var a = List.hd(aValues.contents);
                var b = List.hd(bValues.contents);
                aValues.contents = List.tl(aValues.contents);
                bValues.contents = List.tl(bValues.contents);
                var result;
                try {
                  result = Curry._2(combiner, a, b);
                }
                catch (raw_e){
                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                  Curry._1(obs.onError, e);
                  return Curry._1(subscription.cancel, /* () */0);
                }
                return Curry._1(obs.onNext, result);
              };
              Curry._1(source.subscribeWith, ProtectedObservableObserver$Reaxon.make({
                        onSubscribe: (function (sub) {
                            if (alive.contents) {
                              sourceSub.contents = sub;
                              return /* () */0;
                            } else {
                              return Curry._1(sub.cancel, /* () */0);
                            }
                          }),
                        onComplete: (function (param) {
                            if (alive.contents) {
                              Curry._1(obs.onComplete, /* () */0);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              return 0;
                            }
                          }),
                        onError: (function (x) {
                            if (alive.contents) {
                              Curry._1(obs.onError, x);
                              return Curry._1(subscription.cancel, /* () */0);
                            } else {
                              throw x;
                            }
                          }),
                        onNext: (function (x) {
                            if (alive.contents) {
                              aValues.contents = Pervasives.$at(aValues.contents, /* :: */[
                                    x,
                                    /* [] */0
                                  ]);
                              return combine(/* () */0);
                            } else {
                              return 0;
                            }
                          })
                      }));
              return Curry._1(other.subscribeWith, ProtectedObservableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    otherSub.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onComplete: (function (param) {
                                  if (alive.contents) {
                                    Curry._1(obs.onComplete, /* () */0);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                }),
                              onNext: (function (x) {
                                  if (alive.contents) {
                                    bValues.contents = Pervasives.$at(bValues.contents, /* :: */[
                                          x,
                                          /* [] */0
                                        ]);
                                    return combine(/* () */0);
                                  } else {
                                    return 0;
                                  }
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
