// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(scanner, startItem, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeObservableObserver$Reaxon.make(obs);
              var state = /* record */[/* contents */startItem];
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (sub) {
                              return Curry._1(safe[/* onSubscribe */0], sub);
                            }),
                          /* onComplete */(function (param) {
                              return Curry._1(safe[/* onComplete */1], /* () */0);
                            }),
                          /* onError */(function (x) {
                              return Curry._1(safe[/* onError */2], x);
                            }),
                          /* onNext */(function (x) {
                              var match = state[0];
                              var tmp;
                              if (match !== undefined) {
                                var exit = 0;
                                var value;
                                try {
                                  value = Curry._2(scanner, Caml_option.valFromOption(match), x);
                                  exit = 1;
                                }
                                catch (raw_e){
                                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                                  Curry._1(safe[/* onError */2], e);
                                  tmp = undefined;
                                }
                                if (exit === 1) {
                                  tmp = Caml_option.some(value);
                                }
                                
                              } else {
                                tmp = Caml_option.some(x);
                              }
                              state[0] = tmp;
                              var match$1 = state[0];
                              if (match$1 !== undefined) {
                                return Curry._1(safe[/* onNext */3], Caml_option.valFromOption(match$1));
                              } else {
                                return /* () */0;
                              }
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
