// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(onNext, source) {
  var alive = {
    contents: true
  };
  var subRef = {
    contents: undefined
  };
  var subscription = {
    cancel: (function (param) {
        if (alive.contents) {
          OptionalSubscription$Reaxon.cancel(subRef.contents);
          alive.contents = false;
          return /* () */0;
        } else {
          return 0;
        }
      })
  };
  Curry._1(source.subscribeWith, SafeObservableObserver$Reaxon.make({
            onSubscribe: (function (sub) {
                subRef.contents = sub;
                return /* () */0;
              }),
            onComplete: (function (param) {
                return Curry._1(subscription.cancel, /* () */0);
              }),
            onError: (function (x) {
                Curry._1(subscription.cancel, /* () */0);
                throw x;
              }),
            onNext: (function (x) {
                if (Curry._1(onNext, x)) {
                  return 0;
                } else {
                  return Curry._1(subscription.cancel, /* () */0);
                }
              })
          }));
  return subscription;
}

exports.operator = operator;
/* No side effect */
