// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(onTerminate, source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeObservableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onComplete: (function (param) {
                                  Curry._1(obs.onComplete, /* () */0);
                                  return Curry._1(onTerminate, /* () */0);
                                }),
                              onError: (function (x) {
                                  Curry._1(obs.onError, x);
                                  return Curry._1(onTerminate, /* () */0);
                                }),
                              onNext: (function (x) {
                                  return Curry._1(obs.onNext, x);
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
