// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(mapper, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var safe = SafeObservableObserver$Reaxon.make(obs);
              return Curry._1(source[/* subscribeWith */0], /* record */[
                          /* onSubscribe */(function (sub) {
                              return Curry._1(safe[/* onSubscribe */0], sub);
                            }),
                          /* onComplete */(function (param) {
                              return Curry._1(safe[/* onComplete */1], /* () */0);
                            }),
                          /* onError */(function (x) {
                              return Curry._1(safe[/* onError */2], x);
                            }),
                          /* onNext */(function (x) {
                              var result;
                              try {
                                result = Curry._1(mapper, x);
                              }
                              catch (raw_err){
                                return Curry._1(obs[/* onError */2], Caml_js_exceptions.internalToOCamlException(raw_err));
                              }
                              return Curry._1(obs[/* onNext */3], result);
                            })
                        ]);
            })];
}

exports.operator = operator;
/* No side effect */
