// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(count, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var size = /* record */[/* contents */count];
              return Curry._1(source[/* subscribeWith */0], SafeObservableObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onComplete */(function (param) {
                                  return Curry._1(obs[/* onComplete */1], /* () */0);
                                }),
                              /* onError */(function (x) {
                                  return Curry._1(obs[/* onError */2], x);
                                }),
                              /* onNext */(function (x) {
                                  if (size[0] > 0) {
                                    size[0] = size[0] - 1 | 0;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(obs[/* onNext */3], x);
                                  }
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
