// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedMaybeObserver$Reaxon = require("../../Observers/ProtectedMaybeObserver.bs.js");
var ProtectedObservableObserver$Reaxon = require("../../Observers/ProtectedObservableObserver.bs.js");

function operator(other, source) {
  return {
          subscribeWith: (function (obs) {
              var alive = {
                contents: true
              };
              var innerSub = {
                contents: undefined
              };
              var outerSub = {
                contents: undefined
              };
              var subscription = {
                cancel: (function (param) {
                    if (alive.contents) {
                      OptionalSubscription$Reaxon.cancel(innerSub.contents);
                      OptionalSubscription$Reaxon.cancel(outerSub.contents);
                      alive.contents = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })
              };
              Curry._1(obs.onSubscribe, subscription);
              var innerObserver = ProtectedMaybeObserver$Reaxon.make({
                    onSubscribe: (function (sub) {
                        if (alive.contents) {
                          innerSub.contents = sub;
                          return /* () */0;
                        } else {
                          return Curry._1(sub.cancel, /* () */0);
                        }
                      }),
                    onComplete: (function (param) {
                        if (alive.contents) {
                          Curry._1(obs.onComplete, /* () */0);
                          return Curry._1(subscription.cancel, /* () */0);
                        } else {
                          return 0;
                        }
                      }),
                    onSuccess: (function (x) {
                        if (alive.contents) {
                          Curry._1(obs.onNext, x);
                          Curry._1(obs.onComplete, /* () */0);
                          return Curry._1(subscription.cancel, /* () */0);
                        } else {
                          return 0;
                        }
                      }),
                    onError: (function (x) {
                        if (alive.contents) {
                          Curry._1(obs.onError, x);
                          return Curry._1(subscription.cancel, /* () */0);
                        } else {
                          throw x;
                        }
                      })
                  });
              return Curry._1(source.subscribeWith, ProtectedObservableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  if (alive.contents) {
                                    outerSub.contents = sub;
                                    return /* () */0;
                                  } else {
                                    return Curry._1(sub.cancel, /* () */0);
                                  }
                                }),
                              onComplete: (function (param) {
                                  if (alive.contents) {
                                    Curry._1(other.subscribeWith, innerObserver);
                                    return OptionalSubscription$Reaxon.cancel(outerSub.contents);
                                  } else {
                                    return 0;
                                  }
                                }),
                              onError: (function (x) {
                                  if (alive.contents) {
                                    Curry._1(obs.onError, x);
                                    return Curry._1(subscription.cancel, /* () */0);
                                  } else {
                                    throw x;
                                  }
                                }),
                              onNext: (function (x) {
                                  if (alive.contents) {
                                    return Curry._1(obs.onNext, x);
                                  } else {
                                    return 0;
                                  }
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
