// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedObservableObserver$Reaxon = require("../../Observers/ProtectedObservableObserver.bs.js");

function operator(onSubscribe) {
  return /* record */[/* subscribeWith */(function (obs) {
              var alive = /* record */[/* contents */true];
              var subRef = /* record */[/* contents */undefined];
              var subscription = /* record */[/* cancel */(function (param) {
                    if (alive[0]) {
                      OptionalSubscription$Reaxon.cancel(subRef[0]);
                      alive[0] = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })];
              var $$protected = ProtectedObservableObserver$Reaxon.make(obs);
              var emitter_000 = function (sub) {
                if (alive[0]) {
                  OptionalSubscription$Reaxon.cancel(subRef[0]);
                  subRef[0] = sub;
                  return /* () */0;
                } else {
                  return Curry._1(sub[/* cancel */0], /* () */0);
                }
              };
              var emitter_001 = function (param) {
                return !alive[0];
              };
              var emitter_002 = function (param) {
                if (alive[0]) {
                  Curry._1($$protected[/* onComplete */1], /* () */0);
                  return Curry._1(subscription[/* cancel */0], /* () */0);
                } else {
                  return 0;
                }
              };
              var emitter_003 = function (x) {
                if (alive[0]) {
                  Curry._1($$protected[/* onError */2], x);
                  return Curry._1(subscription[/* cancel */0], /* () */0);
                } else {
                  throw x;
                }
              };
              var emitter_004 = function (x) {
                if (alive[0]) {
                  return Curry._1($$protected[/* onNext */3], x);
                } else {
                  return 0;
                }
              };
              var emitter = /* record */[
                emitter_000,
                emitter_001,
                emitter_002,
                emitter_003,
                emitter_004
              ];
              Curry._1($$protected[/* onSubscribe */0], subscription);
              try {
                return Curry._1(onSubscribe, emitter);
              }
              catch (raw_e){
                return Curry._1(emitter_003, Caml_js_exceptions.internalToOCamlException(raw_e));
              }
            })];
}

exports.operator = operator;
/* No side effect */
