// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(source) {
  return {
          subscribeWith: (function (obs) {
              return Curry._1(source.subscribeWith, SafeObservableObserver$Reaxon.make({
                              onSubscribe: (function (sub) {
                                  return Curry._1(obs.onSubscribe, sub);
                                }),
                              onComplete: (function (param) {
                                  Curry._1(obs.onNext, /* OnComplete */0);
                                  return Curry._1(obs.onComplete, /* () */0);
                                }),
                              onError: (function (x) {
                                  Curry._1(obs.onNext, /* OnError */Block.__(0, [x]));
                                  return Curry._1(obs.onComplete, /* () */0);
                                }),
                              onNext: (function (x) {
                                  return Curry._1(obs.onNext, /* OnNext */Block.__(1, [x]));
                                })
                            }));
            })
        };
}

exports.operator = operator;
/* No side effect */
