// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(item, source) {
  return {
          subscribeWith: (function (obs) {
              var safe = SafeObservableObserver$Reaxon.make(obs);
              var empty = {
                contents: true
              };
              return Curry._1(source.subscribeWith, {
                          onSubscribe: (function (sub) {
                              return Curry._1(safe.onSubscribe, sub);
                            }),
                          onComplete: (function (param) {
                              if (empty.contents) {
                                Curry._1(safe.onNext, item);
                              }
                              return Curry._1(safe.onComplete, /* () */0);
                            }),
                          onError: (function (x) {
                              return Curry._1(safe.onError, x);
                            }),
                          onNext: (function (x) {
                              empty.contents = false;
                              return Curry._1(safe.onNext, x);
                            })
                        });
            })
        };
}

exports.operator = operator;
/* No side effect */
