// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var SafeObservableObserver$Reaxon = require("../../Observers/SafeObservableObserver.bs.js");

function operator(source) {
  return /* record */[/* subscribeWith */(function (obs) {
              return Curry._1(source[/* subscribeWith */0], SafeObservableObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  return Curry._1(obs[/* onSubscribe */0], sub);
                                }),
                              /* onComplete */(function (param) {
                                  return Curry._1(obs[/* onComplete */1], /* () */0);
                                }),
                              /* onError */(function (x) {
                                  return Curry._1(obs[/* onError */2], x);
                                }),
                              /* onNext */(function (x) {
                                  if (typeof x === "number") {
                                    return Curry._1(obs[/* onComplete */1], /* () */0);
                                  } else if (x.tag) {
                                    return Curry._1(obs[/* onNext */3], x[0]);
                                  } else {
                                    return Curry._1(obs[/* onError */2], x[0]);
                                  }
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
