// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Exceptions$Reaxon = require("../../Exceptions.bs.js");
var OptionalSubscription$Reaxon = require("../../Utils/OptionalSubscription.bs.js");
var ProtectedCompletableObserver$Reaxon = require("../../Observers/ProtectedCompletableObserver.bs.js");

function operator(time, scheduler, source) {
  return /* record */[/* subscribeWith */(function (obs) {
              var alive = /* record */[/* contents */true];
              var sourceSub = /* record */[/* contents */undefined];
              var otherSub = /* record */[/* contents */undefined];
              var subscription = /* record */[/* cancel */(function (param) {
                    if (alive[0]) {
                      OptionalSubscription$Reaxon.cancel(sourceSub[0]);
                      OptionalSubscription$Reaxon.cancel(otherSub[0]);
                      alive[0] = false;
                      return /* () */0;
                    } else {
                      return 0;
                    }
                  })];
              return Curry._1(source[/* subscribeWith */0], ProtectedCompletableObserver$Reaxon.make(/* record */[
                              /* onSubscribe */(function (sub) {
                                  if (alive[0]) {
                                    sourceSub[0] = sub;
                                    otherSub[0] = Curry._2(scheduler[/* timeout */1], (function (param) {
                                            otherSub[0] = undefined;
                                            Curry._1(obs[/* onError */2], Exceptions$Reaxon.Timeout);
                                            return Curry._1(subscription[/* cancel */0], /* () */0);
                                          }), time);
                                    return Curry._1(obs[/* onSubscribe */0], subscription);
                                  } else {
                                    return Curry._1(sub[/* cancel */0], /* () */0);
                                  }
                                }),
                              /* onComplete */(function (param) {
                                  if (alive[0]) {
                                    Curry._1(obs[/* onComplete */1], /* () */0);
                                    return Curry._1(subscription[/* cancel */0], /* () */0);
                                  } else {
                                    return 0;
                                  }
                                }),
                              /* onError */(function (x) {
                                  if (alive[0]) {
                                    Curry._1(obs[/* onError */2], x);
                                    return Curry._1(subscription[/* cancel */0], /* () */0);
                                  } else {
                                    throw x;
                                  }
                                })
                            ]));
            })];
}

exports.operator = operator;
/* No side effect */
