// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var EmptySubscription$Reaxon = require("../../Utils/EmptySubscription.bs.js");
var SafeCompletableObserver$Reaxon = require("../../Observers/SafeCompletableObserver.bs.js");

var instance = {
  subscribeWith: (function (obs) {
      var safe = SafeCompletableObserver$Reaxon.make(obs);
      Curry._1(safe.onSubscribe, EmptySubscription$Reaxon.instance);
      return Curry._1(safe.onComplete, /* () */0);
    })
};

function operator(param) {
  return instance;
}

exports.instance = instance;
exports.operator = operator;
/* No side effect */
