// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var EmptySubscription$Reaxon = require("../../Utils/EmptySubscription.bs.js");

var instance = /* record */[/* subscribeWith */(function (obs) {
      return Curry._1(obs[/* onSubscribe */0], EmptySubscription$Reaxon.instance);
    })];

function operator(param) {
  return instance;
}

exports.instance = instance;
exports.operator = operator;
/* No side effect */
